# Generated by Django 3.1.7 on 2021-03-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('deliveryEstimate', models.CharField(blank=True, max_length=10, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('imagePath', models.ImageField(blank=True, null=True, upload_to='')),
                ('about', models.TextField(blank=True, max_length=100, null=True)),
                ('hours', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
